

  # Variables 
  vmImageName: 'ubuntu-latest'
  imageName: 'pythonfunc'
  repo: 'pythonfunc'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: 'python -m pip install --upgrade pip && pip install -r requirements.txt'
    displayName: 'Install dependencies'

- stage: Deploy to dev
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:

          - task: AzureFunctionAppContainer@1
            displayName: 'Azure Function App on Container Deploy: hellworldfunc'
            inputs:
              azureSubscription: 'Visual Studio Enterprise with MSDN (92800e22-a5bd-44b1-a59a-2defd15e82d1)'
              appName: hellworldfunc
              deployToSlotOrASE: true
              resourceGroupName: pythonv3
              slotName: dev
              imageName: 'zanicr.azurecr.io/pythonfunc:latest'

  - stage: Deploy to UAT
  displayName: Deploy stage uat
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:

          - task: AzureFunctionAppContainer@1
            displayName: 'Azure Function App on Container Deploy: hellworldfunc'
            inputs:
              azureSubscription: 'Visual Studio Enterprise with MSDN (92800e22-a5bd-44b1-a59a-2defd15e82d1)'
              appName: hellworldfunc
              deployToSlotOrASE: true
              resourceGroupName: pythonv3
              slotName: uat
              imageName: 'zanicr.azurecr.io/pythonfunc:latest'




